name: Deploy using GitHub Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2  # Use actions/setup-node@v2 instead of v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm install --save-dev @babel/plugin-proposal-private-property-in-object  # Add the missing devDependency
    - run: npm run build --if-present
    - run: npm test
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
          folder: build
